### ISSUE TITLE
Tyrian QOL attempts to delete character

### ISSUE THREAD

**Issue by iRobsie** [KenediaDev/Kenedia.BlishHUD#10]
Logging out with this disabled attempts to delete my character. Not sure why, item delete is even disabled.
Provided is screenshots of my settings, and video of it happening with it disabled, and me disabling and it stopping.

https://github.com/KenediaDev/Kenedia.BlishHUD/assets/71240401/b02bf0bc-3305-487d-97f1-b5352165a11a
![Blish_HUD_L9Q82t4KmQ](https://github.com/KenediaDev/Kenedia.BlishHUD/assets/71240401/d3a05f62-7fd6-44fb-a72b-c7566459cdb8)
![Blish_HUD_KXopVuun6t](https://github.com/KenediaDev/Kenedia.BlishHUD/assets/71240401/e03e9115-2722-4c07-be04-565bf39859fa)

![Blish_HUD_Tqa1IJc1y0](https://github.com/KenediaDev/Kenedia.BlishHUD/assets/71240401/561ac37b-4529-4743-ac14-17ed72d5931a)

brief addition while typing this, looked into the blish hud to see if it would help, the issue is skip cutscenes:

`01:55:32.2889 | INFO  | Kenedia.Modules.QoL.QoL | Initializing Tyrian QoL 1.0.4
01:55:32.2889 | INFO  | Kenedia.Modules.QoL.QoL | Starting Tyrian QoL v.1.0.4
01:55:32.3010 | INFO  | Blish_HUD.Modules.Module | Module "Tyrian QoL (Kenedia.Modules.QoL) v1.0.4" finished loading.
01:55:32.3306 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Gamestate changed to Ingame
01:56:23.2566 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Gamestate changed to CharacterSelection
01:56:28.8763 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Gamestate changed to LoadingScreen
01:56:30.6567 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Gamestate changed to Cutscene
01:56:30.6567 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | SkipCutscene
01:56:30.6567 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Press Escape and wait a bit
01:56:30.9202 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | We are still in the cutscene lets try with mouse.
01:56:31.1761 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Click with the mouse in the bottom right corner.
01:56:34.7572 | INFO  | Kenedia.Modules.QoL.SubModules.SkipCutscenes.SkipCutscenes | Gamestate changed to LoadingScreen
`

**Comment by KenediaDev** [comment]
This is because we can not detect the actual game state. So it's a bit of a
guessing game to know if you are in a cutscene, character selection,
loading screen.....

You either have to live with the fact it sometimes prompts the character
delete or disable skip cutscenes

iRobsie ***@***.***> schrieb am Sa., 30. Sept. 2023, 08:57:
