### ISSUE TITLE
Builds Manager is not found in the Blish HUD

### ISSUE THREAD

**Issue by Kallan007** [KenediaDev/Kenedia.BlishHUD#12]
Builds Manager shows up on the website but not in Module Repo; https://blishhud.com/modules/?module=Kenedia.Modules.BuildsManager. There is an "Error: The following parameter values are incompatible with their definitions: $module_namespaces" on the site.

**Comment by KenediaDev** [comment]
This is because it's only available as a prerelease since it's still beeing developed but can be used already. Enable the option to include prerelease in blishs general settings and make sure to use the latest version of blish.

**Comment by Kallan007** [comment]
OK, thanks for the information on prerelease.
