### ISSUE TITLE
Characters module cannot save Window Borders

### ISSUE THREAD

**Issue by SkoDave** [KenediaDev/Kenedia.BlishHUD#16]
Hi all, I've changed my monitor and I need to change Window Borders to let module works, but after each reboot the values reset. I'm using "mumble link" to launch Blishud ma settings folder is not changed from default, how can I save the settings or check where is the error?

**Comment by SkoDave** [comment]
Nobody can help me please? I have to edit border settings every time... it is awful...

**Comment by KenediaDev** [comment]
Hey,
Please reach out on the Blish hud discord for me as I'll need some logs and eventually even video footage.

Do other settings get saved? The only thing I could think of is Blish doesn't have enough permissions to write a file.

I'll wait for you to contact me on discord.
