### ISSUE TITLE
Switching Characters results in chat box "enter" loop

### ISSUE THREAD

**Issue by Loquatious-Celea** [KenediaDev/Kenedia.BlishHUD#21]
When I pull up the menu to switch Characters using the character add on, I see "Characters" "Logging out..." but instead of swapping characters, the add on seems to open and close the chat window in an endless loop, the chat box looks as if I pressed the enter key over and over, and the logging out animation plays. I attempted to use the auto fix setting, but this had no effect. I multibox using gw2 launch buddy, but my friend who uses the game normally is also having the same issue. 

I'm sure the expansion launch broke this add on, but I wanted to bring this issue up in case no one else had notified you. Thank you for your amazing add - on and for your time!

**Comment by KenediaDev** [comment]
This sounds like your keybinds don't match the game.

Make sure to set them up correctly.
https://blishhud.com/modules/?module=Kenedia.Modules.Characters
