### ISSUE TITLE
Issue with Characters window focus with Blishud 1.1.x+

### ISSUE THREAD

**Issue by SkoDave** [KenediaDev/Kenedia.BlishHUD#24]
I installed Blishud 1.2.0 but noticed the bug already on 1.1.x+ so I was using 1.0.0 (and switched back today)
Sometimes when you "alt+tab" out GW2 and you click again on Characters search window it seems it does not get the focus and you have to click twice to be able to write inside the search text.

Could you please check this behavior?

**Comment by KenediaDev** [comment]
As you mentioned the only thing that changed was the Blish version. It's an issue with Blish itself not the module... Sorry!

**Comment by SkoDave** [comment]
Ok thank you, I'll try to post on blishud
