### ISSUE TITLE
Weird "click" sound on ZoomOut

### ISSUE THREAD

**Issue by Azradox** [KenediaDev/Kenedia.BlishHUD#27]
Hey there,

when using ZoomOut, there es a weird clicking sound every time it triggers (on map reload or moving camera around near a wall and so on), that's absolutely annoying!!! If it's intended to have that sound, please add at least a possibility to disable it in settings.
ZoomOut can't be used right now with pc sound turned on...

Despite that, great module :)

BR

**Comment by KenediaDev** [comment]
Hey, I'm trying to recreate that issue but i dont have any sounds from Zoom Out (which is intended). I'm curious if anything else triggers a sound for you.

Could you record me a video or livestream for me on discord?

**Comment by Azradox** [comment]
No its definitly the zoom out module!
Easy to reproduce: Go on one of the wells in lions arch and move around the mouse near to the ground looking up to you, clicking over clicking. Once I deactivate zoom out with that litte menu and do the same moving, its gone. It sounds like the click of a camera.

**Comment by Azradox** [comment]
And one click you can hear on every map load, when you port in with waypoint :)

**Comment by Azradox** [comment]
Ah video, sure i try, hang on

**Comment by Azradox** [comment]
Whats your discord?

**Comment by KenediaDev** [comment]
kenedia
