### ISSUE TITLE
Characters menu opens itself

### ISSUE THREAD

**Issue by Zyndoras** [KenediaDev/Kenedia.BlishHUD#4]
Hi there,

I have a weird issue where the characters list opens itself everytime when entering / leaving combat.

Video: https://i.gyazo.com/8d4cf6490be9a4d0e1773c267c69b492.mp4

It only seems to happen when the character was switched to via BlishHUD.
Any idea what could cause this?

I use GW2Launcher to start BlishHUD, if that makes a difference.

Thanks for your great work & Cheers!

**Comment by KenediaDev** [comment]
Check your keybind to toggle the menu. You probably have the same keybind set there as you use vor skills/targeting.

**Comment by Zyndoras** [comment]
Nope, that's not it. I just bound the characters-keybind to something in-game (open the shop). 

Pressing the keybind now opens both.
When getting in combat, only Characters opens.

**Comment by KenediaDev** [comment]
I don't do anything with combat detection.

Can you show me your settings?
Do you happen to use R /ALT + R in combat?



Alex Sella ***@***.***> schrieb am Mo., 20. Feb. 2023, 22:09:

**Comment by KenediaDev** [comment]
Please check if clicking R / ALT +R does it.

You are running blish in debug mode, that would be my guess.

Kenedia Gaming ***@***.***> schrieb am Mo., 20. Feb. 2023,
22:21:

**Comment by Zyndoras** [comment]
I do have `R` and `Alt+R` as keybinds. But pressing them does not do anything out of the ordinary.
Also removing those keybinds does not change anything.

Blish is not in debug mode:
![grafik](https://user-images.githubusercontent.com/12675470/220201668-21abf59b-1c68-4ee0-83c4-f6c370ccb2dd.png)

Characters settings:
![grafik](https://user-images.githubusercontent.com/12675470/220201705-584f8632-b488-457d-b24f-e6d682b3fbbc.png)
![grafik](https://user-images.githubusercontent.com/12675470/220201712-e72aee28-4695-4ef0-9f4d-02a60990fdb9.png)
![grafik](https://user-images.githubusercontent.com/12675470/220201730-1d533380-cb74-41f3-99d6-fd44b66401b3.png)

**Comment by KenediaDev** [comment]
This is very odd.

What if you unbind the characters window toggle?

Alex Sella ***@***.***> schrieb am Mo., 20. Feb. 2023, 22:35:

**Comment by Zyndoras** [comment]
> What if you unbind the characters window toggle?

Still opens on combat.

**Comment by KenediaDev** [comment]
The issue persists between sessions?
Did you restart blish? Gw2?

Alex Sella ***@***.***> schrieb am Mo., 20. Feb. 2023, 22:44:

**Comment by Zyndoras** [comment]
Yes, I have this issue since the OCR update

**Comment by KenediaDev** [comment]
Could you join the discord?
I would want some logs. And would eventually send you a test build.

Alex Sella ***@***.***> schrieb am Mo., 20. Feb. 2023, 22:47:

**Comment by Zyndoras** [comment]
Sure, do you have a link?

Btw, it does stop occurring after changing maps!

**Comment by KenediaDev** [comment]
Does it always happen on the same map?
What do you do to start to trigger it again?

https://discord.gg/JzayFRvV

https://discord.com/channels/531175899588984842/1064906680904724621

**Comment by Zyndoras** [comment]
Current workaround: Set BlishHUD's `Cut Scene / Loading Screen` setting to `Always Show` (and restart BlishHUD)
